name: ckb_dart_sdk
version: 0.12.0+1
author: "BaojunCZ<baojun.cz@gmail.com>"
homepage: https://github.com/BaojunCZ/ckb-sdk-dart
description: ckb sdk by dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  dio: ^1.0.3
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  pointycastle: ^1.0.0

dev_dependencies:
  test: ^1.5.1+1